### ISSUE TITLE
RuntimeError: No such operator tutel_ops::cumsum

### ISSUE THREAD

**Issue by sharkdrop** [microsoft/tutel#190]
Hello, thanks for providing such a great work. However, I cannot use tutel successfully. I have followed the library installation steps:

```
* Install Pytorch for NVIDIA CUDA >= 11.3:
        $ python3 -m pip install --user torch==1.10.0+cu113 torchvision==0.11.1+cu113 -f https://download.pytorch.org/whl/torch_stable.html
       

* Install Tutel Online:

        $ python3 -m pip uninstall tutel -y
        $ python3 -m pip install --user --upgrade git+https://github.com/microsoft/tutel@main


        $ python3 ./tutel/setup.py install --user
```

But when I try the followed test:
```
* Quick Test on Single-GPU:

        $ python3 -m tutel.examples.helloworld --batch_size=16               # Test Tutel-optimized MoE + manual distribution
```

The followed error is reported：

```
Traceback (most recent call last):
  File "/root/miniconda3/envs/widenet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/envs/widenet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/tutel-main/tutel/examples/helloworld.py", line 120, in <module>
    output = model(x)
  File "/root/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/tutel-main/tutel/examples/helloworld.py", line 85, in forward
    result = self._moe_layer(input)
  File "/root/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/tutel-main/tutel/impls/moe_layer.py", line 267, in forward
    logits_dtype, (crit, l_aux) = routing()
  File "/root/tutel-main/tutel/impls/moe_layer.py", line 261, in routing
    inequivalent_tokens = inequivalent_tokens,
  File "/root/tutel-main/tutel/impls/fast_dispatch.py", line 158, in extract_critical
    locations1 = compute_location(masks_se[0])
  File "/root/tutel-main/tutel/jit_kernels/gating.py", line 22, in fast_cumsum_sub_one
    return torch.ops.tutel_ops.cumsum(data)
  File "/root/.local/lib/python3.7/site-packages/torch/_ops.py", line 63, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator tutel_ops::cumsum
```

**Comment by ghostplant** [comment]
what about `expert FAST_CUMSUM=0` first?

**Comment by sharkdrop** [comment]
Thank you. I have tried this, and the new error is reported:
```
Traceback (most recent call last):
  File "helloworld.py", line 120, in <module>
    output = model(x)
  File "/root/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "helloworld.py", line 85, in forward
    result = self._moe_layer(input)
  File "/root/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/tutel-0.1-py3.7-linux-x86_64.egg/tutel/impls/moe_layer.py", line 271, in forward
    y = fast_encode(x.to(logits_dtype), crit, self.is_postscore).to(x.dtype)
  File "/root/.local/lib/python3.7/site-packages/tutel-0.1-py3.7-linux-x86_64.egg/tutel/impls/fast_dispatch.py", line 203, in fast_encode
    dispatcher.update(*critial_data[1:], is_postscore=is_postscore)
  File "/root/.local/lib/python3.7/site-packages/tutel-0.1-py3.7-linux-x86_64.egg/tutel/impls/fast_dispatch.py", line 108, in update
    self.func_fwd = jit_kernel.create_forward(self.dtype, indices_[0].is_cuda)
  File "/root/.local/lib/python3.7/site-packages/tutel-0.1-py3.7-linux-x86_64.egg/tutel/jit_kernels/sparse.py", line 35, in create_forward
    ''')
  File "/root/.local/lib/python3.7/site-packages/tutel-0.1-py3.7-linux-x86_64.egg/tutel/impls/jit_compiler.py", line 37, in generate_kernel
    return JitCompiler.create_raw(template)
  File "/root/.local/lib/python3.7/site-packages/tutel-0.1-py3.7-linux-x86_64.egg/tutel/impls/jit_compiler.py", line 26, in create_raw
    raise Exception('CUDA support is disabled during Tutel installation. Please configure CUDA correctly and reinstall Tutel to enable CUDA support, or report Tutel installation logs for help.')
Exception: CUDA support is disabled during Tutel installation. Please configure CUDA correctly and reinstall Tutel to enable CUDA support, or report Tutel installation logs for help.
```

**Comment by ghostplant** [comment]
Gotcha, this problem is not from `tutel::cumsum`. Instead, you may perform an improper installation of Tutel that only enables CPU support rather than CUDA.

The root cause could be an improper CUDA SDK configuration in your system that makes Tutel fail to build up some components, like missing `cuda.h`, `libnccl.so`, etc.

**Suggestion:**
Can you firstly purge old tutel (pip3 uninstall -y tutel), and reinstall the tutel via source (`python3 ./tutel/setup.py install --user`)? This method will show the full log of installing messages, **including error messages**. You may notice what is wrong with the environment. If you can not find the way to fix the environment, you can paste the full installation log here, so that we can help you diagnose the problem.

**Comment by sharkdrop** [comment]
Thank you for your suggestion，I'll have a try.

**Comment by ghostplant** [comment]
> export FAST_CUMSUM=0

Have you tried: `export FAST_CUMSUM=0`

**Comment by 0x6b64** [comment]
I get this error after setting `FAST_CUMSUM=0`

```bash
[1,319]<stderr>:│ /root/.local/lib/python3.9/site-packages/tutel/impls/fast_dispatch.py:108 in │
[1,319]<stderr>:│ update                                                                       │
[1,319]<stderr>:│                                                                              │
[1,319]<stderr>:│   105 │   │   if self.is_cuda != indices_[0].is_cuda:                        │
[1,319]<stderr>:│   106 │   │   │   self.is_cuda = indices_[0].is_cuda                         │
[1,319]<stderr>:│   107 │   │   │   if self.is_cuda not in TutelMoeFastDispatcher.kernel_pool: │
[1,319]<stderr>:│ ❱ 108 │   │   │   │   self.func_fwd = jit_kernel.create_forward(self.dtype,  │
[1,319]<stderr>:│   109 │   │   │   │   self.func_bwd_data = jit_kernel.create_backward_data(s │
[1,319]<stderr>:│   110 │   │   │   │   self.func_bwd_gate = jit_kernel.create_backward_gate(s │
[1,319]<stderr>:│   111 │   │   │   │   TutelMoeFastDispatcher.kernel_pool[self.is_cuda] = sel │
[1,319]<stderr>:│                                                                              │
[1,319]<stderr>:│ /root/.local/lib/python3.9/site-packages/tutel/jit_kernels/sparse.py:21 in   │
[1,319]<stderr>:│ create_forward                                                               │
[1,319]<stderr>:│                                                                              │
[1,319]<stderr>:│    18   if not is_cuda:              [1,319]<stderr>:                                        │
[1,319]<stderr>:│    19 │   return JitCompiler.generate_cpu_kernel(kernel_type=0)              │
[1,319]<stderr>:│    20                                                                        │
[1,319]<stderr>:│ ❱  21   return JitCompiler.generate_kernel({'dtype': get_kernel_dtype(param_ │
[1,319]<stderr>:│    22 │   #define __dtype @dtype@                                            │
[1,319]<stderr>:│    23 │                                                                      │
[1,319]<stderr>:│    24 │   extern "C" __global__ __launch_bounds__(1024) void execute(__dtype │
[1,319]<stderr>:│                                                                              │
[1,319]<stderr>:│ /root/.local/lib/python3.9/site-packages/tutel/impls/jit_compiler.py:40 in   │
[1,319]<stderr>:│ generate_kernel                                                              │
[1,319]<stderr>:│                                                                              │
[1,319]<stderr>:│   37 │   def generate_kernel(keyword_dict, template):                        │
[1,319]<stderr>:│   38 │     for key in keyword_dict:                                          │
[1,319]<stderr>:│   39 │   │   template = template.replace('@%s@' % key, str(keyword_dict[key] │
[1,319]<stderr>:│ ❱ 40 │     return JitCompiler.create_raw(template)                           │
[1,319]<stderr>:│   41 │                                                                       │
[1,319]<stderr>:│   42 │   @staticmethod                                                       │
[1,319]<stderr>:│   43 │   def generate_cpu_kernel(kernel_type):                               │
[1,319]<stderr>:│                                                                              │
[1,319]<stderr>:│ /root/.local/lib/python3.9/site-packages/tutel/impls/jit_compiler.py:29 in   │
[1,319]<stderr>:│ create_raw                                                                   │
[1,319]<stderr>:│                                                                              │
[1,319]<stderr>:│   26 │   def create_raw(source):                                             │
[1,319]<stderr>:│   27 │   │   torch.cuda.init()                                               │
[1,319]<stderr>:│   28 │   │   if not hasattr(tutel_custom_kernel, 'inject_source'):           │
[1,319]<stderr>:│ ❱ 29 │   │   │   raise Exception('CUDA support is disabled during Tutel inst │
[1,319]<stderr>:│   30 │   │   __ctx__ = tutel_custom_kernel.inject_source(source)             │
[1,319]<stderr>:│   31 │   │                                                                   │
[1,319]<stderr>:│   32 │   │   def func(*inputs, extra=[], blocks=[]):                         │
[1,319]<stderr>:╰──────────────────────────────────────────────────────────────────────────────╯
[1,319]<stderr>:Exception: CUDA support is disabled during Tutel installation. Please configure 
[1,319]<stderr>:CUDA correctly and reinstall Tutel to enable CUDA support, or report Tutel 
[1,319]<stderr>:installation logs for help.
[1,176]<stderr>:╭───────────────────── Traceback (most recent call last) ──────────────────────╮
```

**Comment by 0x6b64** [comment]
> Gotcha, this problem is not from `tutel::cumsum`. Instead, you may perform an improper installation of Tutel that only enables CPU support rather than CUDA.
> 
> The root cause could be an improper CUDA SDK configuration in your system that makes Tutel fail to build up some components, like missing `cuda.h`, `libnccl.so`, etc.
> 
> **Suggestion:** Can you firstly purge old tutel (pip3 uninstall -y tutel), and reinstall the tutel via source (`python3 ./tutel/setup.py install --user`)? This method will show the full log of installing messages, **including error messages**. You may notice what is wrong with the environment. If you can not find the way to fix the environment, you can paste the full installation log here, so that we can help you diagnose the problem.

This is the solution. I was missing the cuda toolkit. `apt-get install -y cuda-toolkit`

**Comment by ghostplant** [comment]
I don't suggest you install cuda toolkit over default Ubuntu repository, as they are too old.

You should follow the instruction here: https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu

After CUDA SDK is successfully, please purge previous tutel and do a fresh installation based on those new CUDA SDK libraries.

**Comment by 0x6b64** [comment]
Thanks for the suggestion! I'm using an older driver && once I added nv repo, I was able to select the version that I needed. `add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"`.
