### ISSUE TITLE
INTERNAL ASSERT FAILED at custom_kernel.cpp

### ISSUE THREAD

**Issue by foreveronehundred** [microsoft/tutel#76]
My branch is (v0.1.3), and I got the following assertion fail sometimes when I used the fast_cumsum_sub_one,
```
Traceback (most recent call last):
  File "test_tutel.py", line 5, in <module>
    cumsum_tutel = fast_cumsum_sub_one(matrix, dim=0) + 1
  File "/home/xxx/.local/lib/python3.8/site-packages/tutel-0.1-py3.8-linux-x86_64.egg/tutel/jit_kernels/gating.py", line 81, in fast_cumsum_sub_one
    return get_cumsum_kernel(data.size(0), data.size(1))(data)
  File "/home/xxx/.local/lib/python3.8/site-packages/tutel-0.1-py3.8-linux-x86_64.egg/tutel/jit_kernels/gating.py", line 72, in optimized_cumsum
    base_kernel(mask1.to(torch.int32).contiguous(), locations1)
  File "/home/xxx/.local/lib/python3.8/site-packages/tutel-0.1-py3.8-linux-x86_64.egg/tutel/impls/jit_compiler.py", line 39, in func
    tutel_custom_kernel.invoke_with_source(inputs, __ctx__, use_nvrtc, source)
RuntimeError: (true) == (fp != nullptr) INTERNAL ASSERT FAILED at "/home/xxx/tutel/tutel/custom/custom_kernel.cpp":33, please report a bug to PyTorch. CHECK_EQ fails.
```
To reproduce the problem, I create the a python file (test_tutel.py),
```
#test_tutel.py
import torch
from tutel.jit_kernels.gating import fast_cumsum_sub_one

matrix = torch.randint(0, 100, (10000, 100), device='cuda')
cumsum_tutel = fast_cumsum_sub_one(matrix, dim=0) + 1
```
Please use the following script to run it,
```
git clone https://github.com/microsoft/tutel --branch v0.1.3
python3 ./tutel/setup.py install --user
mpirun -n 8 python test_tutel.py
```
Try to run it repeatedly, I think error will appear within 20 times.

**Comment by ghostplant** [comment]
Hi, the way to run application with `mpirun -n 8 python test_tutel.py` is not correct, since all 8 child process will be executed on the same GPU node-0, so they will be definitely conflict in resources.

The correct way to launch is highlighted in the README.md description:
```
mpiexec -host localhost -x LOCAL_SIZE=8 -x MASTER_ADDR=localhost python3 -m tutel.launcher.run python test_tutel.py
```

**Comment by ghostplant** [comment]
You can also use '-x USE_NVRTC=1' to skip the conflict error above, however, all 8 nodes are still sharing the same GPU node.
