### ISSUE TITLE
Problem from applying pipeline parallel with Tutel's cumsum

### ISSUE THREAD

**Issue by foreveronehundred** [microsoft/tutel#82]
I just got an error when applying Torch pipeline parallel with Tutel's **cumsum**. The problem is caused by the non zero return value of **cuLaunchKernel** in tutel/tutel/custom/custom_kernel.cpp. To investigate the issue, I added printf to tutel/tutel/custom/custom_kernel.cpp to print that return value and found that the value is (**CUDA_ERROR_INVALID_HANDLE** == 400)

From NVidia's docs, I found that the following information about CUDA_ERROR_INVALID_HANDLE,
_This indicates that a resource handle passed to the API call was not valid. Resource handles are opaque types like CUstream and CUevent_

Here is the sample code to reproduce the problem,
```
from tutel.jit_kernels.gating import fast_cumsum_sub_one
from torch.distributed.pipeline.sync import Pipe

import torch

def _initialize_pipeline_parallel(num_nodes, nstages):
    '''
    Initialize pipelining framework.
    Args:
      nstages : Total number of pipeline stages.
    '''
    #print("==> inside initialize-pipeline_parallel :")
    assert num_nodes == 1, "Only single node pipeline parallelism is supported right now"
    from torch.distributed import rpc
    import tempfile
    tmpfile = tempfile.NamedTemporaryFile()
    rpc.init_rpc(
        name="grid_worker",
        rank=0,
        world_size=num_nodes,
        rpc_backend_options=rpc.TensorPipeRpcBackendOptions(
            init_method="file://{}".format(tmpfile.name)
        )
    )

class CumsumModule(torch.nn.Module):
    def __init__(self):
        super(CumsumModule, self).__init__()
        self.param = torch.nn.Parameter(torch.ones(5, 5))
    def forward(self, x):
        x = x + self.param
        x_cumsum = fast_cumsum_sub_one(x, dim=0)
        return x_cumsum

_initialize_pipeline_parallel(1, 2)

input = torch.randint(0, 5, (5, 5), device='cuda:0')
cumsum_module0 = CumsumModule().to(device='cuda:0')
cumsum_module1 = CumsumModule().to(device='cuda:1')
model = torch.nn.Sequential(cumsum_module0, cumsum_module1)
model = Pipe(model)
output = model(input)
```
The following is the error messages,
```
Traceback (most recent call last):
  File "Reproduce.py", line 42, in <module>
    output = model(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/pipeline/sync/pipe.py", line 362, in forward
    self.pipeline.run(batches)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/pipeline/sync/pipeline.py", line 117, in run
    self.compute(batches, schedule, skip_trackers)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/pipeline/sync/pipeline.py", line 257, in compute
    raise exc_info[0].with_traceback(exc_info[1], exc_info[2])
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/pipeline/sync/worker.py", line 79, in worker
    batch = task.compute()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/pipeline/sync/worker.py", line 60, in compute
    return self._compute()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/pipeline/sync/pipeline.py", line 222, in compute
    return batch.call(partition)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/pipeline/sync/microbatch.py", line 70, in call
    return Batch(function(self.value))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "Reproduce.py", line 32, in forward
    x_cumsum = fast_cumsum_sub_one(x, dim=0)
  File "/home/chutsai/.local/lib/python3.8/site-packages/tutel/jit_kernels/gating.py", line 83, in fast_cumsum_sub_one
    return get_cumsum_kernel(data.size(0), data.size(1))(data)
  File "/home/chutsai/.local/lib/python3.8/site-packages/tutel/jit_kernels/gating.py", line 72, in optimized_cumsum
    base_kernel(mask1.to(torch.int32).contiguous(), locations1)
  File "/home/chutsai/.local/lib/python3.8/site-packages/tutel/impls/jit_compiler.py", line 41, in func
    tutel_custom_kernel.invoke(inputs, __ctx__)
RuntimeError: (0) == (cuLaunchKernel(gm.hFunc, gm.blocks.x, gm.blocks.y, gm.blocks.z, gm.threads.x, gm.threads.y, gm.threads.z, 0, nullptr, ppargs.data(), nullptr)) INTERNAL ASSERT FAILED at "/tmp/pip-req-build-u7pfjlvx/tutel/custom/custom_kernel.cpp":146, please report a bug to PyTorch. CHECK_EQ fails.
```
Please help me to solve this issue or tell me if did not use the Tutel correctly. Thanks.

**Comment by ghostplant** [comment]
Thanks for showing this requirement. The current JIT compilation only handles "1 program accessing 1 self-owned device" which doesn't work for other environments.

There is a temp fix for your requirement, can you try this branch: https://github.com/ghostplant/tutel/tree/fix_jit
